---
- name: Allow SSH
  firewalld:
    service: ssh
    state: enabled
    permanent: yes
    immediate: yes

- name: Allow HTTP and HTTPS
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  loop:
    - http
    - https